### ISSUE TITLE
Uncaught TypeError: CodeMirror.fromTextArea is not a function

### ISSUE THREAD

**Issue by richardblondet** [seothemes/html-widget#1]
Hi, thanks for this work!

Your plugin is not working with Wordpress version 4.9.8. Seen in Chrome Version 68.0.3440.106

```
Uncaught TypeError: CodeMirror.fromTextArea is not a function
    at HTMLDocument.<anonymous> (widgets.php:1000)
    at i (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,underscore,shortcode,backbon&load[]=e,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload&ver=4.9.8:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,underscore,shortcode,backbon&load[]=e,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload&ver=4.9.8:2)
```

Breaks the admin page.

Thanks!

**Comment by fallenturtle** [comment]
I'm have this same issue, fwiw. Wordpress v5.0.2
